# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build
on: workflow_dispatch

jobs:
  Build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./install-tldag-version.ps1
    - uses: actions/checkout@v2
      with:
        repository: "tldag/tldag-commons"
        token: ${{secrets.TLDAG_TOKEN}}
    - run: ~/tldag-version/tldag-version.exe 0.0.0 13 tldag-commons/tldag-commons.csproj
    - uses: EndBug/add-and-commit@v7.2.1
